#' Enrich the csv file generated by idealisto function.
#'
#' This function enrichs the csv file generated by idealisto with some other variables related with the current situation of the ads downloaded. It's useful to know if the ads are still online days later or have been removed. If the ad has been removed, vigencia function will tell how many days ago and if the ad is still online it will tell if they have a new price. First you have to import the csv file and then call the function on the data frame object.
#' @param df A data frame object generated by idealisto function and imported later to the enviroment.
#' @param ruta A valid path in your computer where you want to create the csv file. If none given it will generate the csv in the working directory.
#' @return It returns a data.frame object with the new columns.
#' @export
vigencia <- function(df, ruta = NULL) {
  list.of.packages <- c("stringr", "rvest", "httr")
  new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
  if(length(new.packages)>0) {install.packages(new.packages)}
  
  
  library(stringr)
  library(rvest)
  library(httr)
  
  
  desktop_agents <-  c('Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36',
                       'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36',
                       'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36',
                       'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14',
                       'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36',
                       'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36',
                       'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36',
                       'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36',
                       'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36',
                       'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0')
  
  
  
  urls <- as.character(df$Url)
  df$baja <- NA
  df$nuevo_precio <- NA
  df$rebaja_agrup <- NA
  df$MenosDe30 <- NA
  
  start <- Sys.time()
  start_2 <- Sys.time()
  
  for(p in 1:length(urls)) {
    
    x <- GET(urls[p], add_headers('user-agent' = desktop_agents[sample(1:10, 1)]))
    baja <- x %>% read_html() %>% html_nodes("p")
    
    if (as.character(baja[1]) == '<p class="pager-count"> </p>') {
      
      df$nuevo_precio[p] <- x %>% read_html() %>% html_nodes(".h1-simulated") %>% html_text()
      df$nuevo_precio[p] <- as.integer(str_replace_all(string = df$nuevo_precio[p], pattern = " eur/mes|\\.", replacement = ""))
      print(paste("Sigue dado de alta con este precio:", df$nuevo_precio[p], "€."))
      
    } else if (isTRUE(str_detect(baja[1], "Esto puede haber ocurrido porque"))) {
      df$baja[p] <- "Baja sin fecha"
      print(df$baja[p])
    } else {
      df$baja[p] <- str_replace_all(baja[1], "<p>|</p>", "")
      print(df$baja[p])
    }
    
    if (Sys.time() > start_2 + 420) {
      stop_t <- sample(x = 100:120, size = 1)
      print(paste("Para que no se nos cabree Idealista vamos a parar la máquina durante", stop_t, "segundos."))
      Sys.sleep(time = stop_t)
      start_2 <- Sys.time()
    }
    Sys.sleep(sample(x = 0.5:1.2, size = 1))
  }
  
  df$nuevo_precio <- as.integer(df$nuevo_precio)
  
  df$baja <- str_replace_all(string = str_replace_all(string = df$baja, pattern = "El anunciante lo dio de baja el ", replacement = ""), pattern =  "lunes |martes |miércoles |jueves |viernes |sábado |domingo ", replacement = "")
  df$baja <- str_replace_all(string = df$baja, pattern = "Baja \\(sin fecha\\)", replacement = "1 de marzo de 2018")
  
  df$baja[df$baja == "Todos los anuncios pasan el control de calidad en un tiempo aproximado de un día laborable "] <- NA
  
  df$baja <- str_replace_all(string = df$baja, pattern = " de ", replacement = "")
  df$baja <- str_replace_all(string = df$baja, pattern = "enero", replacement = "-01-")
  df$baja <- str_replace_all(string = df$baja, pattern = "febrero", replacement = "-02-")
  df$baja <- str_replace_all(string = df$baja, pattern = "marzo", replacement = "-03-")
  df$baja <- str_replace_all(string = df$baja, pattern = "abril", replacement = "-04-")
  df$baja <- str_replace_all(string = df$baja, pattern = "mayo", replacement = "-05-")
  df$baja <- str_replace_all(string = df$baja, pattern = "junio", replacement = "-06-")
  df$baja <- str_replace_all(string = df$baja, pattern = "julio", replacement = "-07-")
  df$baja <- str_replace_all(string = df$baja, pattern = "agosto", replacement = "-08-")
  df$baja <- str_replace_all(string = df$baja, pattern = "septiembre", replacement = "-09-")
  df$baja <- str_replace_all(string = df$baja, pattern = "octubre", replacement = "-10-")
  df$baja <- str_replace_all(string = df$baja, pattern = "noviembre", replacement = "-11-")
  df$baja <- str_replace_all(string = df$baja, pattern = "diciembre", replacement = "-12-")
  
  df$baja <- as.Date(df$baja, format = "%d-%m-%Y")
  
  df$vigencia <- df$baja - as.Date(df$fecha)
  df$MenosDe30[df$vigencia <= 30] <- "30 días o menos" 
  df$MenosDe30[is.na(df$vigencia)] <- "Sigue de alta"
  
  df$rebaja <- df$Precio - df$nuevo_precio
  df$rebaja_agrup[df$rebaja == 0] <- "Igual" 
  df$rebaja_agrup[df$rebaja > 0 & df$rebaja <= 150] <- "Aumento de 150€ o menos" 
  df$rebaja_agrup[df$rebaja > 150 & df$rebaja <= 350] <- "Aumento de entre 151€ y 350€" 
  df$rebaja_agrup[df$rebaja > 350 & df$rebaja <= 500] <- "Aumento de entre 351€ y 500€" 
  df$rebaja_agrup[df$rebaja > 500] <- "Aumento de más de 450€" 
  
  df$rebaja_agrup[df$rebaja < 0 & df$rebaja >= -50] <- "Rebaja de 50 o menos" 
  df$rebaja_agrup[df$rebaja < -50 & df$rebaja >= -100] <- "Rebaja de entre 51€ y 100€" 
  df$rebaja_agrup[df$rebaja < -100] <- "Rebaja de más de 101€" 
  
  write_csv(x = df, path = paste0("~/","idealisto_",Sys.Date(),".csv"))
  
  stop <- Sys.time()
  diff <- stop - start
  print(diff)
}